### ISSUE TITLE
Balls will sometimes phase through each other especially at high speeds

### ISSUE THREAD

**Issue by IgbarVonSquid** [FairlySadPanda/vrcbce#100]
I've noticed a lot that balls will sometimes pass through each other, usually when colliding at high speed. This also includes the pool cues which will sometimes pass through the cue ball. I haven't looked at the collision code so I don't know if it's handled by Udon or unity physics but I think the culprit is that the Rigidbodies on the balls are using Discrete for Collision Detection. I'd recommend changing it to Continuous Dynamic or Continuous Speculative for more accurate hit detection between balls if this is actually the source of the issue.
Unity documentation with more info: https://docs.unity3d.com/2019.4/Documentation/Manual/class-Rigidbody.html

**Comment by FairlySadPanda** [comment]
The table is written 100% in Udon to be deterministic across clients, which Unity physics isn't. There are better ways of tackling how to do a pool table (especially now we have a sane sync option) but the "totally rebuild the table to fix collisions" change is pencilled in for 2.0.0, which is a long ways out.
