### ISSUE TITLE
Ivylistar table - Can push ball outside

### ISSUE THREAD

**Issue by NiyahVE** [FairlySadPanda/vrcbce#114]
Hello !

The railing system in Ivylistar allow the ball to be pushed out using the cue ; I am unsure if it's done on purpose or not.
Wording hard, here's a video.

https://niyah.eu/i/EWaIvh2pj0.mp4

Thanks everyone for the hard work on that prefab, pretty pog.

**Comment by Legoman99573** [comment]
Its bound to happen regardless and there is more problems than that with the ivylistar table like the white ball spinning of doom.

**Comment by FairlySadPanda** [comment]
White ball spin o' doom is fixed in 1.4.1. We've improved some aspects of the physics for the metal table in 1.4.1, but the nature of the system means it's going to be a bit unstable.
