### ISSUE TITLE
type or namespace "isValid" does not exist in the namespace "Utilities"

### ISSUE THREAD

**Issue by Kicoxyz** [FairlySadPanda/vrcbce#116]
![image](https://user-images.githubusercontent.com/75277551/135577041-ca789d44-d91f-4561-b75b-2bae4f31554b.png)

Receiving these errors in the console after importing VRCBilliards into the Project. Have already tried re-importing the latest SDK, the latest version of UdonSharp (0.20.3 as of writing) and reimporting VRCBilliards by deleting both the FSP and VRCBilliards folders. Just thought I would make an issue to see if there was any other possible fixes.

**Comment by Metamaniac** [comment]
As of commit https://github.com/FairlySadPanda/vrcbce/commit/bb22090affbb68ea92603f78d6f130bffe65ef24, the chance of U# getting confused and causing this should be properly mitigated; will be fixed in next release! (which will be soon) (you can also download the repo directly if you want it early)
