### ISSUE TITLE
Desktop mode camera faces my ceiling?

### ISSUE THREAD

**Issue by Skipyellow** [FairlySadPanda/vrcbce#120]
![screen1 5](https://user-images.githubusercontent.com/92235082/136676789-c2114383-bc39-4828-8d9c-78c0480b764d.png)

this is latest 1.5 version MOON metal table

**Comment by BluWizard10** [comment]
I've had this issue before with all the Pool Tables in my world. The solution I have to this is changing the Camera's clipping planes.

Go to the `desktop_camera` object and increase the value for "Near" on the Clipping Planes until you don't see the Ceiling anymore. Doing this moves the camera's minimum viewing area closer to the table.
