### ISSUE TITLE
A couple of feature requests.

### ISSUE THREAD

**Issue by Legoman99573** [FairlySadPanda/vrcbce#14]
I have a couple of feature requests and you can decide if you want to do them or not.

1. I know the one Terri00 made had how to guides on each gamemode, but is it possible to add it back so that players who never played before don't get confused straight out of the box or just have them show up per gamemode?
2. For 8-ball, allow all the regular colors for solids and stripes as a seperate gamemode. (I assume it will require alot of work most likely)
3. For teams, enable 2 extra pool sticks and cycle through so that your teammate isn't hogging it most of the time. (this is rare, but sometimes it can be annoying for those who want to play)

**Comment by FairlySadPanda** [comment]
Hey: these are all solid suggestions - I'll break them out into three issues now.

**Comment by FairlySadPanda** [comment]
Could you give some more detail for this -> https://github.com/FairlySadPanda/vrcbce/issues/19

Not 100% sure what you'd want here - photos would help

**Comment by Legoman99573** [comment]
![image](https://user-images.githubusercontent.com/7460704/120088373-57d32100-c0b5-11eb-9cb0-23d9385607ac.png)
basically how these balls appear without them being changed for each team or player vs player

**Comment by FairlySadPanda** [comment]
Thanks: I'll see about adding this in this week.
