### ISSUE TITLE
Add some gamemodes like Pro mode

### ISSUE THREAD

**Issue by MrDummyNL** [FairlySadPanda/vrcbce#23]
There are some forks with:
- another simulation code
- pro mode (no lock stick, no aim line and hit ball point)
- practice mode, where you can move balls what you want
- save / load practice mode....

So that is a lot for a fork. What can you do here? Pro mode might good add, others are just extra.

**Comment by FairlySadPanda** [comment]
It'd be best for each PR to be a separate feature. So in this instance, PRs for better simulation code, the pro mode and better practice mode separately would be ideal.

I may reject a PR if it's too big, but generally I'll do my best to review whatever comes in.
