### ISSUE TITLE
Figure out a better PR workflow

### ISSUE THREAD

**Issue by FairlySadPanda** [FairlySadPanda/vrcbce#26]
I'm having issue with my tooling for PR reviews. I'm using the VSCode Github Pull Request and Issue extension, but given folks are wanting to merge from their forks this leaves me in a weird situation where I can't do what I want, which is:

1. Get given a PR
2. Review it without having to make a new one I actually made
3. Accept it, potentially make edits to it
4. Merge

I'll need to read up on better ways of managing this.

**Comment by Legoman99573** [comment]
Or just make a seperate branch is easier than modifying the master branch then trying to push a PR as that tends to cause a lot of issues if the master branch changes when they made modifications.
