### ISSUE TITLE
Quest Support

### ISSUE THREAD

**Issue by FairlySadPanda** [FairlySadPanda/vrcbce#3]
v0.2.0 has no official support for Quest. This is because it was superfluous to the priority of making a smaller, easier-to-edit prefab.

Quest support is required for v1.0.0, as the table needs to have close to feature parity with the original prefab.

The priority here is simplicity. Personally, when doing cross-compatible work "Quest-first" is the correct route. So for 1.0.0, the code needs to fully work assuming Quest-level hardware is the default. (That means that we switch off PC-only features, or allow those features to work on Quest too).

**Comment by techanon** [comment]
Just a heads up that I had a Quest user test the pool table (v0.3.0 at the time) in my theater world and it worked fine. Only issue was an occasional flash which was from the reflection probe afaict. Just disconnect that from the main pool script inspector and add an extra null check for the probe variable on line PoolStateManager:2040-ish, then it seemed to work fine.

Here's a video clip for posterity/proof:
https://cdn.discordapp.com/attachments/836760608044613682/844107937177665576/Pooltable_Quest.mp4

**Comment by FairlySadPanda** [comment]
Thanks Tech. 1.0.0-pre2 will automatically remove any reflection probe when booted on Quest/2.
