### ISSUE TITLE
XSStandard shader broken

### ISSUE THREAD

**Issue by Legoman99573** [FairlySadPanda/vrcbce#31]
Not sure if some parts were accidently left out or anything even though I only see mcuestick material using it.
![image](https://user-images.githubusercontent.com/7460704/120130543-106b9400-c18c-11eb-9907-bf877a1cccc0.png)

**Comment by FairlySadPanda** [comment]
Good spot. Think this is a deprecated material and can be ignored. I'll make a push now with it removed, so the next release won't include it.

**Comment by Legoman99573** [comment]
Ill close myself since next release wont have the broken shader and stuff ;)
