### ISSUE TITLE
Problem with Udon Sharp

### ISSUE THREAD

**Issue by KazuSama10** [FairlySadPanda/vrcbce#35]
So I imported the latest 1.1.1 Pool Table and when I try to test it by pressing play and using CyanEmu, "All U# compile errors have to be fixed before you can enter playmode!" And then when I try to build and test from the control panel, it says,"The the VRCSDK build was aborted at the request of the 'UdonSharpBUildCompile' VRCSDKBuildRequestedCallback" I have SDK 3 and udon sharp in there of course. I dragged and dropped the table into world and just deleted the Logger chat. And then I completely removed the entire folder from the project and things are back to normal. Am I missing something or did I do something wrong here!

**Comment by FairlySadPanda** [comment]
Hey:

1. Make sure you're using the latest VRC SDK3 build and the latest U#.
2. If you're getting a U# compile issue, you should get error logs in the Unity console saying why.

**Comment by KazuSama10** [comment]
I made sure and yes, everything is up to date. The error is: Assets\vrcbce-1.1.1\Assets\FSP\Utilities\InteractToggle.cs(7,6): error CS0579: Duplicate 'AddComponentMenu' attribute

Also another is: Assets\vrcbce-1.1.1\Assets\FSP\Utilities\InteractToggle.cs(13,30): error CS0111: Type 'InteractToggle' already defines a member called 'Interact' with the same parameter types

I also did test the older versions and they worked fine except that the desktop view by pressing E is just gray with the line from the cue. The difference is that the older versions had a unity package while the recent one just has the zip file, I don't know if that is the difference because im just dragging the extracted zip file into the assets. I would have been fine using the older versions if it wasn't for the gray screen you get when in desktop view. And I dont know if thats an issue with my project, like the light baking or something. Sorry this is my first ever world so im very new to this.

**Comment by KazuSama10** [comment]
> Hey:
> 
> 1. Make sure you're using the latest VRC SDK3 build and the latest U#.
> 2. If you're getting a U# compile issue, you should get error logs in the Unity console saying why.
> 
> I'll need the error logs so I can debug.

I made sure and yes, everything is up to date. The error is: Assets\vrcbce-1.1.1\Assets\FSP\Utilities\InteractToggle.cs(7,6): error CS0579: Duplicate 'AddComponentMenu' attribute

Also another is: Assets\vrcbce-1.1.1\Assets\FSP\Utilities\InteractToggle.cs(13,30): error CS0111: Type 'InteractToggle' already defines a member called 'Interact' with the same parameter types

I also did test the older versions and they worked fine except that the desktop view by pressing E is just gray with the line from the cue. The difference is that the older versions had a unity package while the recent one just has the zip file, I don't know if that is the difference because im just dragging the extracted zip file into the assets. I would have been fine using the older versions if it wasn't for the gray screen you get when in desktop view. And I dont know if thats an issue with my project. Sorry this is my first ever world so im very new to this.

(EDIT)Actually... There are a bunch of red errors, like alot, I think im not putting it in the right way(EDIT)

**Comment by FairlySadPanda** [comment]
I see at least one problem, there was no uploaded package for 1.1.1. I've put it up:
https://github.com/FairlySadPanda/vrcbce/releases/download/1.1.1/vrcbce_1.1.1.unitypackage

Delete the Assets/FairlySadPanda and Assets/VRCBilliardsCE folders then import.

Fingers crossed that solves your issue, or I can try and debug tomorrow.

**Comment by KazuSama10** [comment]
> I see at least one problem, there was no uploaded package for 1.1.1. I've put it up:
> https://github.com/FairlySadPanda/vrcbce/releases/download/1.1.1/vrcbce_1.1.1.unitypackage
> 
> Delete the Assets/FairlySadPanda and Assets/VRCBilliardsCE folders then import.
> 
> Fingers crossed that solves your issue, or I can try and debug tomorrow.

YESSSSSSSSSSSSSSSSSSSSSSSSSSS! DUDE! You saved my vrchat world! Thank you so much it works perfectly now!
