### ISSUE TITLE
Interaction Text of End Game Button is wrong

### ISSUE THREAD

**Issue by esnya** [FairlySadPanda/vrcbce#36]
There are two Interaction Text with a value of "Enable Table". Maybe one of them is a property of "End Game Button".

Is the correct value "End Game"?

https://github.com/FairlySadPanda/vrcbce/blob/master/Assets/VRCBilliardsCE/PoolTable.prefab#L20982

**Comment by FairlySadPanda** [comment]
Good spot. That's a really easy fix too, can put it in the next release.

**Comment by Metamaniac** [comment]
Has been fixed for awhile now, closing.
