### ISSUE TITLE
4-ball bug: unexpected yellow-white swap

### ISSUE THREAD

**Issue by MrDummyNL** [FairlySadPanda/vrcbce#41]
version 1.1.2 has weird bug: each turn, the white ball suddenly swap with yellow ball. Every player turn!
This bug was not in Harry version.

Please fix the bug.

**Comment by Codel1417** [comment]
1.1.1 replicated

**Comment by FairlySadPanda** [comment]
I've not forgotten about this bug: it doesn't show up in local testing, so I'll be needing to do some in-client testing which is quite a bit slower. It'll be addressed for 1.1.5.

**Comment by MrDummyNL** [comment]
Confirmed indeed white-yellow swap problem in 1.1.4. Hope you can solve it. 
Sometimes if you hit wrong ball, it still accept because it swap again suddenly.

**Comment by FairlySadPanda** [comment]
This is an urgent priority now but I cannot promise a fast fix. It's unclear what has broken, and in my view the game modes are badly written and fragile.

I'm intending to disassemble the game mode code and make it actually legible. At the moment, Jpn/Kor 4-ball, 8-ball and 9-ball are basically mashed together in giant if-elses. This is *terrible*. Much like the menu rewrite, the desktop toggle rewrite, and the cue rewrite, I'm prioritizing getting the code into a stable situation.

I'd appreciate some help here for folks wanting a faster fix. If folks can nail down which release broke this feature, I can drill down specifically what may have broke it and issue a patch.

**Comment by FairlySadPanda** [comment]
As a side-note, the game mode refactor will then allow folks to implement new game modes. I know folks have really wanted to tackle adding new modes, and I've been wanting to add Snooker for six months.

**Comment by FairlySadPanda** [comment]
Diagnosed and fixed in 8960880a9bb206348365e82c05bea9e4b172deec.

1.1.5 will feature a fix.

**Comment by FairlySadPanda** [comment]
Fixed in 1.1.5.
