### ISSUE TITLE
Don't forget the version number :)

### ISSUE THREAD

**Issue by MrDummyNL** [FairlySadPanda/vrcbce#43]
When you upgrade the pool table package to 1.1.2, i am looking weird at the version number scoreboard: it still shows v1.1.1

I did import package again, and it's still v1.1.1. It was not my mistake with Prefab Variant.
So, next time, if you want publish new update: don't forget change also the version number on the score board. :-)

**Comment by MrDummyNL** [comment]
With release of 1.1.4, i thought i still see 1.1.3 on scoreboard?

Did you forget it, or is it indeed changed to 1.1.4?

**Comment by FairlySadPanda** [comment]
1.1.5 has the correct version number. An editor script will be needed to help with this in the future.
