### ISSUE TITLE
Desktop Mode is completly grey..

### ISSUE THREAD

**Issue by annoyedNurse** [FairlySadPanda/vrcbce#44]
So i actually dont know what is happening here and what to do :/ 

![Unbenannt](https://user-images.githubusercontent.com/85455621/120935891-2e457580-c705-11eb-8d4c-93e3f873c355.png)
![Unbenannt2](https://user-images.githubusercontent.com/85455621/120935931-6947a900-c705-11eb-937b-449a8b8e8125.png)

**Comment by FairlySadPanda** [comment]
Not sure: the camera needs to cull everything but layer 23 (legacy, want to fix it) and then the pool table etc needs to be on that layer as well. You'll need to name the layer something for it to show up in Unity.

**Comment by annoyedNurse** [comment]
i will try this. thanks alot. i love this pool table alot. :)
