### ISSUE TITLE
Pool Cues return to origin position/rotation and not relative to table on game reset

### ISSUE THREAD

**Issue by Foomaring** [FairlySadPanda/vrcbce#47]
If a pool table is converted to a pick-up object, the pool cues initially follow the table.  If the game is reset, the pool cues return to the initial transform of the pool table prior to pick-up, instead of following the current position of the table.

https://user-images.githubusercontent.com/70248206/122130745-173e0c00-ce06-11eb-95e7-62102ca717d2.mp4

**Comment by FairlySadPanda** [comment]
Will be actioned next release.

**Comment by FairlySadPanda** [comment]
Fixed in next release! 1.1.4 will support you placing the spawn locations of the cues anywhere, meaning that if you want them on a rack somewhere, hidden in the world, or moved with the table on a pickup, it will now work! :)

**Comment by FairlySadPanda** [comment]
As said, I've improved this a lot. Let me know if you'd like this further improved.
