### ISSUE TITLE
Remove $ from team text.

### ISSUE THREAD

**Issue by MrDummyNL** [FairlySadPanda/vrcbce#53]
![VRChat_1920x1080_2021-06-16_01-59-09 664](https://user-images.githubusercontent.com/37593786/122670481-9ba3dc80-d1c2-11eb-96ce-bf2a5ed3a54b.png)
Also See: [https://imgur.com/a/4qU7Izf](https://imgur.com/a/4qU7Izf)

Until version 1.1.3, this extra unneeded $ will visible if you play in team mode.
Can you remove it?

**Comment by Legoman99573** [comment]
Easy to pinpoint and removed it, Just waiting for PR to be merged.
