### ISSUE TITLE
Error with latest update.

### ISSUE THREAD

**Issue by NataIynn** [FairlySadPanda/vrcbce#58]
Error with latest update: 

[<color=#FF00FF>UdonSharp</color>] Assets/VRCBilliardsCE/Scripts/PoolCue.cs(62,38): Udon runtime exception detected!
  An exception occurred during EXTERN to 'VRCSDKBaseVRCPlayerApi.__IsUserInVR__SystemBoolean'.
      Parameter Addresses: 0x00000019, 0x0000003F
  
  Object reference not set to an instance of an object

[<color=#FF00FF>UdonSharp</color>] Assets/VRCBilliardsCE/Scripts/PoolStateManager.cs(491,50): Udon runtime exception detected!
  An exception occurred during EXTERN to 'VRCSDKBaseVRCPlayerApi.__IsUserInVR__SystemBoolean'.
      Parameter Addresses: 0x00000622, 0x00000051
  
  Object reference not set to an instance of an object

**Comment by FairlySadPanda** [comment]
Expected if you're not using CyanEmu. The default VRC SDK does not provide an output when calling Networking.LocalPlayer in editor runs.

(CyanEmu is highly recommended!)
