### ISSUE TITLE
Cues reset in weird position

### ISSUE THREAD

**Issue by MrDummyNL** [FairlySadPanda/vrcbce#60]
You moved 2 cues now to side, upstand in last version.

Problem by game end: cues are now put back but in less nice way:
![VRChat_1920x1080_2021-06-23_00-17-44 626](https://user-images.githubusercontent.com/37593786/123013759-1b999480-d3c5-11eb-9003-4743be6939a6.png)

This can done better (old versions are just good), so check why it goes in wrong position.

**Comment by NataIynn** [comment]
I have this as well.

**Comment by FairlySadPanda** [comment]
Fully aware of this, it's a consequence of the rewrite to cues (if this is the worst thing that's happened with a total overhaul, I'm pretty pleased).

I'll address this tonight, but the big to-do atm is the 4-ball bug.

**Comment by FairlySadPanda** [comment]
Fixed in 1.1.5.
