### ISSUE TITLE
Pool Table Error (REPOST)

### ISSUE THREAD

**Issue by NataIynn** [FairlySadPanda/vrcbce#61]
I've tested with CyanEmu, and VRC Test builds and no errors like this is found. Only when I build & Publish to VRChat. Older version of this works fine, no issues. However I ignored the error and just published it anyways. It works fine after testing it regardless. Atleast on desktop. 

Edit: Using tried using the latest unity package file,  and the included hot fix, but still same.

Error with latest update: 

[<color=#FF00FF>UdonSharp</color>] Assets/VRCBilliardsCE/Scripts/PoolCue.cs(62,38): Udon runtime exception detected!
  An exception occurred during EXTERN to 'VRCSDKBaseVRCPlayerApi.__IsUserInVR__SystemBoolean'.
      Parameter Addresses: 0x00000019, 0x0000003F
  
  Object reference not set to an instance of an object

[<color=#FF00FF>UdonSharp</color>] Assets/VRCBilliardsCE/Scripts/PoolStateManager.cs(491,50): Udon runtime exception detected!
  An exception occurred during EXTERN to 'VRCSDKBaseVRCPlayerApi.__IsUserInVR__SystemBoolean'.
      Parameter Addresses: 0x00000622, 0x00000051
  
  Object reference not set to an instance of an object

**Comment by FairlySadPanda** [comment]
Hey, this is expected! CyanEmu doesn't run when the build is going up.

I'll have a word with Prefabs and see if I can find a good way of surpressing this error.

**Comment by FairlySadPanda** [comment]
I've added some guards to help with builds that hopefully will stop these false crashes from happening.
