### ISSUE TITLE
There's a collider on the logger canvas.

### ISSUE THREAD

**Issue by esnya** [FairlySadPanda/vrcbce#70]
The `VRC Ui Shape` adds a non-trigger collider if one does not exist. This makes it an obstacle in play.

The `VRC Ui Shape` can be removed since it has no interaction with the Logger. Alternatively, add a box collider with trigger to avoid it.

**Comment by Metamaniac** [comment]
Got rid of it and there doesn't seem to be any negative difference, nor collider on the logger, so I'm assuming it's fixed.
