### ISSUE TITLE
PoolStateManager keeps spitting out NullReferenceException

### ISSUE THREAD

**Issue by ballfu** [FairlySadPanda/vrcbce#77]
`NullReferenceException: Object reference not set to an instance of an object
VRCBilliards.PoolStateManager.ApplyTableColour (System.Boolean isTeam2Turn) (at Assets/VRCBilliardsCE/Scripts/PoolStateManager.cs:2238)
VRCBilliards.PoolStateManager.OnRemoteGameOver () (at Assets/VRCBilliardsCE/Scripts/PoolStateManager.cs:2322)
VRCBilliards.PoolStateManager.ReadNetworkData () (at Assets/VRCBilliardsCE/Scripts/PoolStateManager.cs:2015)
VRCBilliards.PoolStateManager.RefreshNetworkData (System.Boolean newIsTeam2Playing) (at Assets/VRCBilliardsCE/Scripts/PoolStateManager.cs:1944)
VRCBilliards.PoolStateManager.Reset () (at Assets/VRCBilliardsCE/Scripts/PoolStateManager.cs:1477)
UnityEngine.GameObject:AddComponent(Type)
UdonSharpEditor.UdonSharpEditorUtility:GetProxyBehaviour(UdonBehaviour, ProxySerializationPolicy) (at Assets/UdonSharp/Editor/UdonSharpEditorUtility.cs:422)
UdonSharpEditor.UdonSharpEditorManager:CreateProxyBehaviours(List`1) (at Assets/UdonSharp/Editor/UdonSharpEditorManager.cs:984)
UdonSharpEditor.UdonSharpEditorManager:RunAllUpdates(List`1) (at Assets/UdonSharp/Editor/UdonSharpEditorManager.cs:470)
UdonSharpEditor.UdonSharpEditorManager:OnChangePlayMode(PlayModeStateChange) (at Assets/UdonSharp/Editor/UdonSharpEditorManager.cs:447)
UnityEditor.EditorApplication:Internal_PlayModeStateChanged(PlayModeStateChange) (at C:/buildslave/unity/build/Editor/Mono/EditorApplication.cs:302)`

**Comment by FairlySadPanda** [comment]
Fixed in 1.2.2: don't name Udon events Reset. D:
