### ISSUE TITLE
Table Emission Color Broken/Not Working

### ISSUE THREAD

**Issue by BluWizard10** [FairlySadPanda/vrcbce#85]
Using 1.3.0. For some reason, the emission color doesn't ever update on the Table when a person's turn is changed (doesn't change to Orange). I've tried deleting the prefab and reinstalling it completely, and still doesn't work.

**Comment by BluWizard10** [comment]
> Looks like we've got this [issue](https://github.com/FairlySadPanda/vrcbce/pull/67)  again?

Yeah, I've had to manually set it to "Realtime" and yet, the colors still don't change at all.

**Comment by Metamaniac** [comment]
@esnya It actually doesn't matter what the emission's GI is set to, all that setting does is control how the emission value with Unity Standard is handled with Unity's GI systems (whether it gets baked, or gets applied with Realtime GI if people are using that). Unity 2019 actually lets us disable emission touching GI at all, which is what I've done as of commit https://github.com/FairlySadPanda/vrcbce/commit/e510cfc480cfc3a5b8f06ab948c6886fecf68282

This issue ended up being a scripting issue. For whatever reason the logic that actually *changes* the emission color at the end of the day was both **commented out** and **written poorly**, the latter likely explaining the former. Not sure when, how, or why it was like that, but I fixed it :) https://github.com/FairlySadPanda/vrcbce/commit/98619d4d9bb0cc8e2e029cedecaf2a39d2bc92f0
