### ISSUE TITLE
That broke everything of my unity

### ISSUE THREAD

**Issue by Just1Chat** [FairlySadPanda/vrcbce#88]
Well i added the 8 pool and when i wanted to build and test that send me a error i tried to restart but when i restart the VRCHAT sdk pannel dont show anymore !
![image](https://user-images.githubusercontent.com/77287618/130161698-4d81ecf5-049f-4b89-ad67-f5ba9d020bd8.png)

**Comment by Just1Chat** [comment]
![image](https://user-images.githubusercontent.com/77287618/130161759-881811fe-2ba2-4205-93b4-e99583b09c8a.png)

**Comment by FairlySadPanda** [comment]
This is a rare VRC SDK bug: you have to re-import the SDK safely to fix it, which basically works like the 2019 update did - you open an empty scene, save the project, quit, remove the VRC SDK, Udon and UdonSharp folders from your project, re-open the project and then re-import the SDK then UdonSharp.

**Comment by Just1Chat** [comment]
its done thank you !
