### ISSUE TITLE
Font asset increases bundle size

### ISSUE THREAD

**Issue by esnya** [FairlySadPanda/vrcbce#89]
## Issue
`SourceHanSansJP-Regular SDF.asset` takes 4.4MB on my build. This is not a small value for VRChat Worlds. Japanese fonts have a lot of characters, so they generate very large textures and font data.

###  Using Fallback with VRChat
If you are not particular about Japanese fonts, you can use TMPro's built-in font assets. Japanese characters are displayed as `□` in the editor. However, in the VRChat client, it will automatically fall back to the Japanese font.

### Atlas Population Mode to Static
Set the `Atlas Population Mode` of the `TMPFontAsset` to `Static`. Then TMPro seems to generate an atlas texture that contains only the characters used in the scene on build. In this case, the (huge) font data was not included in the bundle. This method should be used with caution if you have dynamically changing strings.

## Versions
- Unity 2019.4.29f1
- VRCSDK3-WORLD-2021.08.11.15.16_Public
- UdonSharp v0.20.2
- vrcbce 1.3.1
- Target Platform: Windows

P.S.
`Table-Main-Metallic.png` takes 5.3MB. MetallicSmoothnesMap should not be affected by compression as much as NormalMap or AlbedoMap.

**Comment by Metamaniac** [comment]
Addressed both of these in https://github.com/FairlySadPanda/vrcbce/commit/c290a5f77760f25c508d4d072e2a6c3bbc5f26d4 and https://github.com/FairlySadPanda/vrcbce/commit/48ecea64675b71ce26f54a54ee0c5e4972206347 :)
