### ISSUE TITLE
Pc mode camera issue

### ISSUE THREAD

**Issue by BamberBoozler** [FairlySadPanda/vrcbce#90]
When using the table in pc mode, pressing E just shows a solid black screen instead of the top down view.

**Comment by NiyahVE** [comment]
Might have to do with your culling settings ; try to change the culling settings of the camera used by vrcbce.

**Comment by BamberBoozler** [comment]
> Might have to do with your culling settings ; try to change the culling settings of the camera used by vrcbce.

I don't recall there being a camera in the prefab, do you have to manually link one?

**Comment by NiyahVE** [comment]
The top view is done by using a camera, there's one in the prefab somewhere ; I can't give more informations right now since i'm on phone ! sorry

**Comment by Metamaniac** [comment]
Could you provide some more detail (screenshots of your hierarchy/inspector would help) as well as the world you're reproducing this in?

**Comment by BamberBoozler** [comment]
> Could you provide some more detail (screenshots of your hierarchy/inspector would help) as well as the world you're reproducing this in?

not sure which parts of the inspector you need but here is this

![pool](https://user-images.githubusercontent.com/50951969/130370470-b73804b6-40db-4556-82e9-8a4601ece2d2.png)

**Comment by BamberBoozler** [comment]
ah heck, just noticed the desktop camera one, its to high, above the ceiling of the building.
