### ISSUE TITLE
Having the scoreboard on both sides during a game

### ISSUE THREAD

**Issue by Ruuubickk** [FairlySadPanda/vrcbce#99]
Having to run around the table to see the current score is a bit frustrating, so this would be a simple solution.

**Comment by Legoman99573** [comment]
in some worlds, they will put on the wall somewhere where its visible, but this is a good solution as not all world owners do this

**Comment by Metamaniac** [comment]
> 
> 
> in some worlds, they will put on the wall somewhere where its visible, but this is a good solution as not all world owners do this

This would be controlled with a toggle in one of the UdonBehaviors, on by default, but allowing creators to disable the functionality if they manually place the score canvas somewhere else :)

**Comment by Metamaniac** [comment]
Forgot to close this!
